# Generated by Django 3.0.2 on 2020-03-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_orders_cimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='giftcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('validity', models.DateField()),
                ('customerid', models.IntegerField()),
            ],
            options={
                'db_table': 'giftcard',
            },
        ),
    ]
