# Generated by Django 3.0.2 on 2020-03-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_giftcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='giftcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
