# Generated by Django 3.0.2 on 2020-03-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_giftcard_giftcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='status',
            field=models.CharField(default='expiered', max_length=20),
            preserve_default=False,
        ),
    ]
